# Generated by Django 4.2.5 on 2023-11-05 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Cart_id',
            new_name='cart_id',
        ),
    ]
